### ISSUE TITLE
Improve wobbly

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#103]
Here is a list of things to be done:

- [ ] ~~Increase model spring count - will improve grab accuracy~~

- [ ] Calculate minimum mass based on friction and spring_k . Currently, if mass is sufficiently small, the wobbly model will "freak out" and make the window expand indefinitely. A simple workaround is to just increase mass.

**Comment by soreau** [comment]
Another option is to [hard code mass as 15](https://github.com/compiz-reloaded/compiz/blob/master/plugins/wobbly.c#L46).
As a side note, I would like to see [friction](https://github.com/compiz-reloaded/compiz/blob/master/metadata/wobbly.xml.in#L33) and [spring_k](https://github.com/compiz-reloaded/compiz/blob/master/metadata/wobbly.xml.in#L41) handled as floats. For instance I have friction 1.5 and spring_k 8 in compiz but can't test that in wayfire since these are ints.
