### ISSUE TITLE
HELP: Wayfire stretching ulauncher and treating it like a regular application

### ISSUE THREAD

**Issue by 0reoKing** [WayfireWM/wayfire#1088]
Hello I am new to wayfire and I enable tiling plugin and I set ulauncher as default launcher however when I launch  ulauncher it is treated like a regular window and is stretched as well making it unusable.

**Comment by ammen99** [comment]
Hello, as far as I know, ulauncher does not natively support Wayland, so you might need to start it via `GDK_BACKEND=x11 ulauncher`.

Alternatively, just specify that ulauncher's window should never be tiled by using this option: https://github.com/WayfireWM/wayfire/wiki/Configuration#simple-tiletile_by_default

I'm closing this issue since I hope this info is enough, but of course feel free to reach out if it still doesn't work.

**Comment by 0reoKing** [comment]
> Hello, as far as I know, ulauncher does not natively support Wayland, so you might need to start it via `GDK_BACKEND=x11 ulauncher`.
> 
> Alternatively, just specify that ulauncher's window should never be tiled by using this option: https://github.com/WayfireWM/wayfire/wiki/Configuration#simple-tiletile_by_default
> 
> I'm closing this issue since I hope this info is enough, but of course feel free to reach out if it still doesn't work.

Sorry I still don't understand how to prevent ulauncher from being tiled.
