### ISSUE TITLE
 Cube crashes a second after returning to desktop

### ISSUE THREAD

**Issue by jsmaniac** [WayfireWM/wayfire#1116]
**Describe the bug**

The cube works find when pressing Ctrl+Alt+LeftMouseButton, and I can stay with the cube rotated as long as I want. When I let go of the key, it returns so that a face of the cube takes the entire screen, and crashes a second after that.

I tried restoring a copy I had of the default config, doesn't seem to change anything. It used to work fine a short while ago, so it might be one of the recent commits?

**To Reproduce**

Ctrl+Alt+LeftMouseButton, move around, release, wait 1-2 seconds.

**Expected behavior**

no crash

**Screenshots or stacktrace**

[wayfire-cube-crash.log](https://github.com/WayfireWM/wayfire/files/6136121/wayfire-cube-crash.log)

**Wayfire version**

git latest commit (reinstalled just now to test)

**Comment by ammen99** [comment]
The fix for the crash while screen recording is active seems to not be enough, can you try #1119 ?

**Comment by droc12345** [comment]
In chasing down another problem, I ran into this one also. I'm using the latest git for both wayfire and wlroots. 
Once I added the following patch to wlroots, the cube quit crashing. Don't know if it's the right fix, but it works for me.
The patch was trivial and it turns off an assert on checking for a null buffer. So either that assert shouldn't be there OR you are somehow sending a null buffer when the cube demo keys/mouse are released. Haven't chased it down any further than that, just wanted to let you know what I've found out.

Adding this because the append wasn't working for me.
--- a/render/gles2/renderer.c	2021-03-16 12:16:06.694837613 -0500
+++ b/render/gles2/renderer.c	2021-03-16 12:41:17.020270079 -0500
@@ -35,7 +35,6 @@
 		struct wlr_renderer *wlr_renderer) {
 	struct wlr_gles2_renderer *renderer = gles2_get_renderer(wlr_renderer);
 	assert(wlr_egl_is_current(renderer->egl));
-	assert(renderer->current_buffer != NULL);
 	return renderer;
 }

**Comment by ammen99** [comment]
@droc12345 @jsmaniac Have any of you been able to try #1119? It should fix the issue without patching wlroots.

**Comment by droc12345** [comment]
I tried 1119 and it didn't help the cube crash, didn't hurt anything, I'm running with it on the git version, this is what gets triggered in wlroots (also a git version).

assert(renderer->current_buffer != NULL);

Which tells me that a NULL buffer is being passed to the renderer. 

In the wlroots 0.12 release, that assert doesn't exist, thus no triggering/crash.

I haven't tried the wlroots 0.12 version with the git version of wayfire, I'm not even sure if wayfire git will compile against wlroots last release instead of the git. I'll check that out in the next few days.

**Comment by ammen99** [comment]
I have managed to reproduce the issue, and tracked it down to the setting of cursor images. Can you check #1119 again? @jsmaniac @droc12345

**Comment by droc12345** [comment]
Yes, the patch for cursors fixed the cube crash problem.

**Comment by ammen99** [comment]
@droc12345 thanks for confirming, i'll merge the PR.
