### ISSUE TITLE
Views visible on multiple outputs

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wayfire#12]
Currently, views are tied to outputs in such a way that makes it impossible to render view on more than one output at a time. This is mostly noticeable when dragging windows from one output to another, the window is cut off until it is on the other output.

**Comment by ammen99** [comment]
Having views float between outputs can be difficult because of the way wayfire handles output - they are almost completely independent - they have a separate set of workspaces, separate plugin instances(cube/expo), etc.

However, there is a way to solve this problem without breaking the current model:

1. Make views maintain a list of their visible outputs. A view retains it's primary output, which is used for all workspace operations. The list of visible outputs is updated each time a view is moved, resized, or its transformation changed, and view's damage is applied to all outputs it is visible on

2. A view is visible on a secondary output, if it is visible on its primary output, its geometry intersects the second output and the the second output doesn't have a custom renderer.

3. If the user activates a view (for example by clicking on it) on an output which is different from the view's main output, then the view's primary output is updated to the output where the activity came from. There are a few things to decide here: Which "activities" would qualify as enough to change the view's output? Clicking on them certainly does, but what about switcher or workspace switching?

In this way, we can easily have multi-output windows which behave relatively well and integrate all plugins.

**Comment by ammen99** [comment]
Another idea that came from our IRC discussion: simply show some animation whenever a view is moved from one output to the other. Windows spanning over multiple outputs aren't that useful anyway
