### ISSUE TITLE
Virtual memory usage skyrockets with foot terminal when switching workspaces

### ISSUE THREAD

**Issue by ericonr** [WayfireWM/wayfire#1244]
**Describe the bug**

Foot will create a new buffer when it needs to render a frame and a workspace switch has happened. It also won't discard the previous buffer because something is still using it, so virtual memory usage jumps in increments of foot's buffer size.

**To Reproduce**

1. Enable plugin Viewport Switcher (not sure this matters)
2. Launch foot, launch some constantly refreshing program inside foot (pipes or htop work). Leave foot focused
3. Switch to another workspace, wait for a few seconds (enough for foot to have something to render)
4. Check memory usage
5. Switch back to foot's workspace
6. Go back to 4, see memory usage increase after each switch+wait.

If I try to reproduce it with `wf-recorder` running, it appears to behave correctly. No bug can be observed. Same appears to happen with `wdisplays`.

**Expected behavior**

Memory usage remains constant, like it does if I remain in the workspace or if the terminal doesn't have any program running that creates output.

This behavior can't be observed on Sway, from my testing.

**Wayfire version**

0.7.2 and from git

- [log.txt](https://github.com/WayfireWM/wayfire/files/6804157/log.txt) <- foot's WAYLAND_DEBUG log
- [mem.txt](https://github.com/WayfireWM/wayfire/files/6804159/mem.txt) <-- steps performed with timestamps from debug log

The diff between `/proc/pidof foot/maps` after two desktop switches looks like (this was with minimum buffer size instead of the default 500M):

```diff
8a9,10
> 00007f9da97dc000   5276K rw-s- memfd:foot-wayland-shm-buffer-pool (deleted)
> 00007f9da9d03000   5276K rw-s- memfd:foot-wayland-shm-buffer-pool (deleted)
42c44
< 00007f9dac212000   2040K rw---   [ anôn ]
---
> 00007f9dac210000   2048K rw---   [ anôn ]
177c179
<  total            53384K
---
>  total            63944K
```

I was told to open an issue here. @soreau couldn't reproduce, but @dnkl managed to reproduce it.

**Comment by dnkl** [comment]
I now believe this is (mostly) foot's fault. I've been looking at foot's SHM buffer management code for other reasons. Two things meant that foot, under certain conditions, kept adding new buffers instead of either freeing, or re-using them.

It is triggered when foot is required to allocate a new buffer because the compositor hasn't yet released the previous one, but then later, the compositor releases **both**. At this point, we have **two** buffers that can be re-used. Switching workspace in Wayfire triggered this.

The first bug in foot caused one of these two buffers to be tagged as "busy" (owned by the compositor), while in fact it wasn't. Foot never touches (frees, or re-uses) a buffer owned by the compositor. Thus, this meant that this buffer was now "locked", and never freed. If we at this point switched workspace in Wayfire, we ended up adding yet another buffer. This one was subsequently locked as well. Thus, switching workspace back and forth kept adding buffers.

The second bug was that foot would keep multiple, re-usable buffers around. Under normal circumstances, we never _have_ multiple re-usable buffers; we either have a single one (normal behavior in wlroots based compositors), or two that we switch between (KDE does this). In the latter case, one of the two buffers are always owned by the compositor, and thus not considered re-usable. Note that foot _would_ purge all these buffers if e.g. the foot window was resized. But only those that are owned by foot. The first bug prevented this from happening.

I can no longer reproduce the issue described in this issue. It would be awesome if you, @ericonr, also could test a foot master branch build.

**Comment by ericonr** [comment]
@dnkl this fixed it, thanks a lot!

Will close the issue.

**Comment by ahmadraniri1994** [comment]
I don't know if my problem is related, but when I want to close foot terminal via close button, it makes wayfire hangs for a second and then wayfire is crashed or force closed. Is it foot's fault or any other reasons? Thanks
