### ISSUE TITLE
Keyboard layout per window

### ISSUE THREAD

**Issue by AlexJakeGreen** [WayfireWM/wayfire#1297]
It would be good if Wayfire can remember keyboard layout per window.

Similar example in Sway: https://github.com/artemsen/swaykbdd
Similar example for X11: https://github.com/qnikst/kbdd

**Comment by ammen99** [comment]
I think this could easily be a plugin with a very similar mode of operation to the sway example you linked. Instead of Sway's IPC it would directly listen to our `view-focused` signal, and call the corresponding `wlr_keyboard_*` functions.

That being said, I don't plan on adding this to core Wayfire, even if someone implements it, it will remain an external plugin.

**Comment by AlexJakeGreen** [comment]
@ammen99 Yes, indeed, it's really easy to implement as an external plugin. Thanks for telling which signal to use, it was very helpful.
For those who are looking for the similar feature I leave a link to a plugin I started to work on [wayfire-kbdd-plugin](https://github.com/AlexJakeGreen/wayfire-kbdd-plugin)
