### ISSUE TITLE
Change keyboard layout with shortcut

### ISSUE THREAD

**Issue by JustinDroege** [WayfireWM/wayfire#1326]
Maybe there is already a option for it, but is there any way to change the keyboard layout with a shortcut?

This would be a nice feature when this is not already in the current state

**Comment by AlexJakeGreen** [comment]
What is a "shortcut" in this case?

This is an example how I configured keyboard layouts switch using CapsLock key
```
[input]
*** skipped ***
xkb_layout = pl,ru
xkb_model = pc104
xkb_options = grp:caps_toggle,grp_led:caps
xkb_rules = evdev
xkb_variant = ,ruu
```

Also I use a plugin to "remember" keyboard layout per window https://github.com/AlexJakeGreen/wayfire-kbdd-plugin

**Comment by Voklen** [comment]
This can be achieved by setting `xkb_options` the same way the layout and variants are set. So although I don't think it's necessary to add any new features for this, I think it could be beneficial to make it clear how to do this from the default `wayfire.ini` since this is an essential feature if you have multiple layout. Something like (of course commented out)
```ini
[input]
xkb_layout = us,fr
xkb_variant = dvorak,bepo
xkb_options = grp:win_space_toggle
```
and then in the wiki link to https://man.archlinux.org/man/xkeyboard-config.7#Switching_to_another_layout

**Comment by ammen99** [comment]
> This can be achieved by setting `xkb_options` the same way the layout and variants are set

Yeah absolutely. Feel free to send a PR for the README :)

In the meantime, I am closing this issue, since there isn't much else to be done about it.
