### ISSUE TITLE
Simple test-able live image?

### ISSUE THREAD

**Issue by IngwiePhoenix** [WayfireWM/wayfire#1378]
So I have been testing out several desktop environments and left my rant [at Reddit](https://www.reddit.com/r/linuxquestions/comments/r9y5vy/accessibility_nightmare_a_rant_after_a_several/). Through the comments, I ended up finding Wayfire (again, actually) and when I looked at the example config, I was mindblown that the feature I wanted was [right in the example config!](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini#L97-L99)

So, long story short, I REALLY want to try out Wayfire - it might be exactly what I have been wanting since I started my journey, and might be the answer I need. Therefore, I looked at the installation options.

But installing it into my Ubuntu system might cause more troubble than it's worth. So I wanted to ask if there was a simple LiveUSB or something I could pop into my PC to just boot into it and try it out before I use it? That would be really useful to have.

I am currently in the process of learning more about how DEs function and how their stack/setup works. So reading through Wayfire is really interesting - albeit my griefences with C++ `auto` aside, I think I am starting to understand how this is supposed to work... but there will be more questions coming up in the future from me, that is for sure.

Thank you in advance and have a great day :)

**Comment by ammen99** [comment]
Hi, a live ISO is out-of-scope for this project. However, another project, Garuda Linux, has a distribution flavor with Wayfire, although their setup is heavily customized (though, you can remove all of the customizations, since the config file controls basically everything). There is also [carbonOS](https://gitlab.com/carbonOS) though that's still experimental as far as I know. 

 That being said, soreau has created packages for Ubuntu/Debian. You can try them out, see his blog for instructions: http://blog.northfield.ws/wayfire-ubuntu-packages/ (for users, the instructions are at the bottom). If you don't like wayfire, you can just disable the PPA and revert the upgrade .. I'd say this is likely the easiest option for you to try it out :)

Closing this issue, if you have any questions, don't hesitate to ask us on Matrix/IRC/Github.
