### ISSUE TITLE
Are we supposed to be using wf::config::compound_option_t?

### ISSUE THREAD

**Issue by AhoyISki** [WayfireWM/wayfire#1452]
Looking at the header files, it seems like `wf::config::compound_option_t` is more "sophisticated" than `wf::config::compound_list_t`, as the latter seems to be literally just a regular vector of tuples.

I'm asking this because none of the regular plugins seem to use `wf::config::compound_option_t`, all are using the other one, as `wf::option_wrapper_t<wf::config::compound_list_t>`. 

Also, if the answer is yes, would this option look different in the xml file?

**Comment by ammen99** [comment]
I think the confusion here comes because of the implementation. Here's a summary of what each of these types is (spoiler: the same on different abstraction levels):

- `compound_list_t` : As you have mentioned, this is a **value**, i.e a list of tuples
- `compound_option_t`: This is the option type in wf-config. E.g. if you would use `config->get_option('any/compound_option')`, the returned object will be of type `compound_option_t`
- `option_wrapper_t<compound_list_t>` : This is a wrapper around a `compound_option_t` which lets you more easily load a specific option (instead of going through the config manager) and also some other ease-of-use features.

Compound options are not special here. Take for example int options. `int` is the value, `option_t<int>` is the wf-config option type, `wf::option_wrapper_t<int>` is what plugins use.

Closing, but feel free to ask more questions if my explanation was not clear enough ;)

**Comment by AhoyISki** [comment]
Is there some "canonical" way to load an option that's not listed in the xml file? Right now, the solution that I have is really janky, and you're obviously not supposed to use it:
```cpp
try {
    wf::option_wrapper_t<Type> option{"option/name"};
    \** Code if the option exists *\
} catch (...) {
    \** Code if it doesn't
}
```
I say this because in my [plugin](https://github.com/AhoyISki/wayfire-firedecor) you would have default options that apply to all windows, but you may also specify individual options to be overridden in specific windows, e.g. replace the `active_border` option on just views that match `title is "something"`, but keep everything else the same.

This seems to be fundamentally incompatible with something like `compound_list_t`, as you would have to create a list for each option, since, from my testing, if any of the entries in the list haven't been set, the list is invalid.

Also, it doesn't seem like I can create a `compound_list` of `view_matcher`s. Is that correct?

**Comment by ammen99** [comment]
> Also, it doesn't seem like I can create a `compound_list` of `view_matcher`s. Is that correct?

Nope, view matchers are not an option type, view matchers are a special wrapper around a string option.

> Is there some "canonical" way to load an option that's not listed in the xml file? Right now, the solution that I have is really janky, and you're obviously not supposed to use it:

You can directly get the option from the config manager https://github.com/WayfireWM/wf-config/blob/master/include/wayfire/config/config-manager.hpp#L44 (the config manager object is `wf::get_core().config`).

`option_wrapper_t` is, well, a wrapper and provides a much nicer syntax for everything, but it is specifically designed for options present in the XML files.


> This seems to be fundamentally incompatible with something like `compound_list_t`, as you would have to create a list for each option, since, from my testing, if any of the entries in the list haven't been set, the list is invalid (in the case I create a `compound_list_t` with all options).

Yeah, compound options don't have default values. It is a good question whether this should be allowed. The current implementation does not allow it, because compound options are supposed to be a list of values. For example, in [command], having a default value for the options doesn't make sense at all.

I guess we can make this optional? I.e. have an optional default value in the XML, if it is present, then the compound option entry can be left out, otherwise, it has to be in the config file. Would this be helpful to your plugin?

**Comment by AhoyISki** [comment]
> I guess we can make this optional? I.e. have an optional default value in the XML, if it is present, then the compound option entry can be left out, otherwise, it has to be in the config file. Would this be helpful to your plugin?

I feel like there should be something like that, but I also feel like we should have a simple way to check if an option was set in the config file, for the purpose of e.g., defining an option in terms of another, in case it wasn't already set. Right now, the only way to do that is to check if an option still has the default value (I think), and that's not reliable, because you can't know if the user wants the default value, or just simply have not changed it.

**Comment by ammen99** [comment]
> I feel like there should be something like that, but I also feel like we should have a simple way to check if an option was set in the config file, for the purpose of e.g., defining an option in terms of another, in case it wasn't already set. Right now, the only way to do that is to check if an option still has the default value (I think), and that's not reliable, because you can't know if the user wants the default value, or just simply have not changed it.

This assumes that there is a config file. Wayfire does not make this guarantee, there are other config backends which don't have it. So this information can't be provided.

> So is there any way to get their value without an xml file? Maybe a way to use any string as a view matcher?

Take a look at the matcher implementation. If you want to use an `std::string` as a criteria, I'm pretty sure you can get it working in 20 lines or so :)

https://github.com/WayfireWM/wayfire/blob/master/src/core/matcher.cpp
