### ISSUE TITLE
Support ext-session-lock

### ISSUE THREAD

**Issue by kiasoc5** [WayfireWM/wayfire#1494]
This will improve screenlocking security.

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/tree/main/staging/ext-session-lock

https://github.com/swaywm/swaylock/commit/3e84316ce294e329c23a8c2b2c89cd6c0cfbd182

(Refs from https://github.com/labwc/labwc/issues/215)

**Comment by lcolitti** [comment]
Not sure if you've started this already, but if not, I started an implementation here. It's not finished, but it seems to at least cover basic locking and unlocking using swaylock.

Does the general approach look reasonable? Any feedback?

Also, I noticed that using swaylock, the background is displayed but the indicator is not. I'm not sure if this is due to a bug in my code. One theory I had to explain this is that it's to do with subsurfaces. swaylock renders the indicator using a subsurface; maybe wlr-surface-node doesn't support subsurfaces?
