### ISSUE TITLE
Support for window opacity

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wayfire#1500]
Setting the opacity in programs like Alacritty does not change anything. The only way I found to do this is with the alpha plugin, but that is just affecting everything and thus making it pretty unusable for my case.
I would be very pleased if wayfire supported this.
Thanks!

**Comment by ammen99** [comment]
> Setting the opacity in programs like Alacritty does not change anything.

That's weird, because my terminal is also Alacritty and I have it semi-transparent. In general, having the app support this is much better than having Wayfire adjust the opaqueness of a window, because when Wayfire does it, the text also becomes transparent (which is generally not what you want). I'd suggest trying to see how you can fix Alacritty, maybe ask the developers and/or try it in sway/river/gnome/whatever to make sure this is not a Wayfire bug where Wayfire interprets the alpha channel wrongly (if this works in e.g. Sway then feel free to open a new issue).

**Comment by UltraBlackLinux** [comment]
Oh crap, I did exactly [this](https://github.com/alacritty/alacritty/issues/5808#issuecomment-1019730829)
