### ISSUE TITLE
How to properly setup wayfire in nixos

### ISSUE THREAD

**Issue by prehonor** [WayfireWM/wayfire#1502]

**Comment by ammen99** [comment]
You need to give some more details and explain what the problem is. All I know about Nix is that someone was trying to package Wayfire for it, and as far as I know they have succeeded.

**Comment by Electrostasy** [comment]
NixOS Wayfire user here. Wayfire 0.7.2 is packaged in NixOS/nixpkgs, but there is no module to enable it like there is for Sway. You have to add it to your packages list manually:
```nix
{ pkgs, ... }:

{
  environment.systemPackages = [ pkgs.wayfire ];
}
```
You can set up the configuration file in `~/.config/wayfire.ini` normally by following the [wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration) and then start Wayfire from TTY.

For wf-shell and wcm, you could try using a function in nixpkgs ([`pkgs.wayfireApplications-unwrapped.wrapWayfireApplication`](https://github.com/NixOS/nixpkgs/blob/49299adf4e95037c1692fca941d6370e453e2855/pkgs/applications/window-managers/wayfire/applications.nix#L14)) to wrap them with Wayfire like so, and adding it to your `systemPackages`:
```nix
{ pkgs, ... }:

{
  wayfireApplications = pkgs.wayfireApplications-unwrapped.withPlugins (plugins: [ plugins.wf-shell ]);
}
```

In addition, if you want to use external plugins, you can try packaging them yourself and wrap Wayfire so that the plugin *.so and *.xml files are present in the `WAYFIRE_PLUGIN_PATH` and `WAYFIRE_PLUGIN_XML_PATH` environment variables when launching Wayfire, see more [in this issue](https://github.com/WayfireWM/wayfire-plugins-extra/issues/78#issuecomment-1121987109).

**Comment by prehonor** [comment]
> NixOS Wayfire user here. Wayfire 0.7.2 is packaged in NixOS/nixpkgs, but there is no module to enable it like there is for Sway. You have to add it to your packages list manually:
> 
> ```nix
> { pkgs, ... }:
> 
> {
>   environment.systemPackages = [ pkgs.wayfire ];
> }
> ```
> 
> You can set up the configuration file in `~/.config/wayfire.ini` normally by following the [wiki](https://github.com/WayfireWM/wayfire/wiki/Configuration) and then start Wayfire from TTY.
> 
> For wf-shell and wcm, you could try using a function in nixpkgs ([`pkgs.wayfireApplications-unwrapped.withPlugins`](https://github.com/NixOS/nixpkgs/blob/49299adf4e95037c1692fca941d6370e453e2855/pkgs/applications/window-managers/wayfire/applications.nix#L16-L19)) to wrap them with Wayfire then and adding it to your `systemPackages`:
> 
> ```nix
> { pkgs, ... }:
> 
> {
>   environment.systemPackages = [
>     (pkgs.wayfireApplications-unwrapped.withPlugins (plugins: [ plugins.wf-shell ]))
>   ];
> }
> ```
> 
> In addition, if you want to use external plugins, you can try packaging them yourself and wrap Wayfire so that the plugin *.so and *.xml files are present in the `WAYFIRE_PLUGIN_PATH` and `WAYFIRE_PLUGIN_XML_PATH` environment variables when launching Wayfire, see more [in this issue](https://github.com/WayfireWM/wayfire-plugins-extra/issues/78#issuecomment-1121987109). Though you may find that some external plugins require Wayfire git/master versions (which also works pretty well!).

This is my configuration.nix: https://pastebin.com/KpsBK2Fn and wayfire.ini https://pastebin.com/J9fM7P9d, 
After I opened kitty or some app else , my cursor disappeared

**Comment by Electrostasy** [comment]
My cursor does disappear while typing in kitty if the cursor is above the kitty window, but if I move the mouse again, it reappears; the cursor also doesn't seem to disappear in other programs like libreoffice. For kitty there is [this configuration option](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.mouse_hide_wait) you can add to `~/.config/kitty/kitty.conf` to change the length of time until the cursor is hidden.

I noticed you use a `wayfire-unstable` package in your configuration.nix, if the problem persists, could you share the derivation for it and if possible a minimally reproducible configuration?

**Comment by prehonor** [comment]
> My cursor does disappear while typing in kitty if the cursor is above the kitty window, but if I move the mouse again, it reappears; the cursor also doesn't seem to disappear in other programs like libreoffice. For kitty there is [this configuration option](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.mouse_hide_wait) you can add to `~/.config/kitty/kitty.conf` to change the length of time until the cursor is hidden.
> 
> I noticed you use a `wayfire-unstable` package in your configuration.nix, if the problem persists, could you share the derivation for it and if possible a minimally reproducible configuration?
> 
> Additionally, what hardware are you running Wayfire on? I noticed some Nvidia settings in your configuration.nix, and I'm not sure how well Wayfire interacts with them, as I've only got access to an AMD GPU. Upon further inspection there seems to be some issues in wlroots for [disappearing cursors under Nvidia/nouveau](https://gitlab.freedesktop.org/search?group_id=9759&scope=issues&search=Disappearing+cursor). Setting the environment variable `WLR_NO_HARDWARE_CURSORS=1` fixed it for some people.

 WLR_NO_HARDWARE_CURSORS=1 works ! Thank you for your help!
