### ISSUE TITLE
GTK dialogs which are drawn with decorated set to False display incorrectly

### ISSUE THREAD

**Issue by spl237** [WayfireWM/wayfire#1634]
**Describe the bug**
Setting the "decorated" property of a GTK window to FALSE results in a window with a frame and title drawn by the compositor

**To Reproduce**

Build and run the following code:
```
#include <stdio.h>
#include <stdlib.h>
#include <gtk/gtk.h>

int main (int argc, char *argv[])
{
    gtk_init (&argc, &argv);
    GtkWidget *win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_window_set_decorated (GTK_WINDOW (win), FALSE);
    gtk_widget_show_all (win);
    gtk_main ();
    return 0;
}
```

**Expected behavior**
The window should be drawn as the contents only - there should be no visible frame, title, or buttons.

**Screenshots or stacktrace**
https://www.dropbox.com/s/pk6wtad0y5udm3u/20221125_12h34m03s_grim.png

**Wayfire version**
0.7.4 Debian bookworm version; also happens with current top-of-tree from GitHub

**Comment by soreau** [comment]
Does this work?

```
#include <stdio.h>
#include <stdlib.h>
#include <gtk/gtk.h>

int main (int argc, char *argv[])
{
    gtk_init (&argc, &argv);
    GtkWidget *win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
    gtk_widget_show_all (win);
    gtk_window_set_decorated (GTK_WINDOW (win), FALSE);
    gtk_main ();
    return 0;
}
```

**Comment by spl237** [comment]
It does in that trivial example, but it doesn't in the code where I was actually using it, which launches an undecorated dialog as a child to another window; I'll try to put together another simple test case to show that.

(It's not an ideal solution in any case, as it has to be done programmatically rather than being set in the UI file.)

**Comment by spl237** [comment]
Ah - no, on a bit of fiddling, the reason it doesn't work in my code is because the window is set undecorated in the UI file. If I don't set the window to undecorated in the UI file and then set it undecorated programmatically in the code, it is drawn correctly without decorations.

This code does need to work both under Wayfire and under X, so I'll need to fiddle with it and see if I can get something that behaves correctly in both.

Is it likely to be possible to fix Wayfire so that it is possible to just set undecorated in a UI file?

**Comment by spl237** [comment]
On further investigation, the change suggested above doesn't quite do the right thing.

It does display the window without the spurious frame and titlebar, but the window is also shown without the shading around it. Under mutter, displaying a window as undecorated loses the window furniture, but still shows it as a shaded window - this is what I would expect undecorated to do, but it doesn't seem to in Wayfire.

**Comment by soreau** [comment]
The reason this doesn't work as expected is because gtk doesn't send `ORG_KDE_KWIN_SERVER_DECORATION_MANAGER_MODE_NONE` like it should for undecorated windows, instead is sends `ORG_KDE_KWIN_SERVER_DECORATION_MANAGER_MODE_CLIENT`. So as far as wayfire is concerned, the window should be drawing its own decoration and therefore shadow. Since gtk has no decoration for 'shadow-only', mutter is most likely treating it specially. There is a plugin for wayfire called wayfire-shadows. It's a subproject in wayfire-plugins-extra or you can build it standalone from [here](https://github.com/timgott/wayfire-shadows). Enable the plugin and the option therein 'Include windows that have their own decoration' and you should have what you want.

**Comment by spl237** [comment]
That's really helpful, thank you!

Is it worth my hacking the GTK backend to send the correct decortion manager mode value? Would that mean I didn't need to use the plugin? (I have quite a lot of patches in the version of GTK I use anyway, so one more won't make much difference!)

Many thanks again.

**Comment by soreau** [comment]
Even if you hacked gtk to send `NONE`, you'd still need the wayfire-shadows plugin because the default wayfire decoration plugin doesn't have a shadow-only decoration, either. Ideally either gtk would have a shadow-only CSD or wayfire have a shadow-only SSD (and that's where wayfire-shadows plugin comes in).

**Comment by spl237** [comment]
Understood - I'll have a play and see what looks good. Many thanks again for all the help.
