### ISSUE TITLE
Virtual desktop different wallpaper

### ISSUE THREAD

**Issue by ArcticMage** [WayfireWM/wayfire#1655]
Is it possible or could be possible to have different wallpaper for each virtual desktop (or workspace)?

John

**Comment by soreau** [comment]
Yes, it is possible to write such a plugin. You could do something similar to annotate plugin but put the overlays on the [wf::scene::layer::BACKGROUND](https://github.com/WayfireWM/wayfire/blob/master/src/api/wayfire/scene.hpp#L402) layer instead of [wf::scene::layer::TOP](https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/annotate.cpp#L191)

**Comment by ammen99** [comment]
As @soreau said, it is in theory possible to write a plugin for this. There is also https://codeberg.org/valpackett/wf-wallpaper which might support what you need already. In any case, this is a feature belonging to a plugin outside of the main repo, so closing this issue.
