### ISSUE TITLE
view-focused after view-pre-unmapped 

### ISSUE THREAD

**Issue by AlexJakeGreen** [WayfireWM/wayfire#1680]
**Describe the bug**
When we have 2 and more windows, and we close the current focused one, then another window becomes active (it accepts keyboard input, the border and titlebar have color of a focused window), but the "view-focused" signal is not observed until I click on this window.

It looks like was working in 0.7, but doesn't in the latest git version.

If this is expected behavior, could you please provide an example how to retrieve current active view.

**Wayfire version**
git

**Comment by ammen99** [comment]
I've been thinking about this a bit more and I came to the following conclusion: your kbdd plugin would most likely benefit from being a global plugin (e.g. not with a per-output plugin instance), as otherwise you have to keep track of views going to different outputs, etc. In that case, it would be better to use the lower-level keyboard-focus-changed signal (https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/seat.cpp#L283) and try to cast the scenegraph node to a view_node_t to figure out whether a view was focused or not.

Of course, what you described is still a bug and should be fixed.
