### ISSUE TITLE
Blender file dialog does not react to clicks

### ISSUE THREAD

**Issue by EoceneMiacid** [WayfireWM/wayfire#1860]
**Describe the bug**

Blender's file open dialog is almost unusable under Wayfire. The application itself appears to work ok. The file dialog does not seem to get proper focus. Wiith some persistence, it can be used with keyboard controls.

**To Reproduce**

Open the file dialog in Blender (File > Open) and try to navigate the dialog with the mouse

**Expected behavior**

The file dialog should respond normally to mouse clicks.

**Wayfire version**
0.8.0-f1d524df (Aug  3 2023, branch 'master'), wayfire-git

**Comment by EoceneMiacid** [comment]
Is there something I can do to help with this?

This modal dialog focus problem hampers the usability of a lot of popular apps (Gimp, Steam, Blender).

**Comment by ammen99** [comment]
@EoceneMiacid If this problem has started occurring recently, you could bisect to see which commit has happened recently.

Otherwise, you'd have to debug it. It would be interesting to know whether the dialog is a toplevel or an unmanaged xwayland surface (Wayfire prints that in the log with `-d`). If it is unmanaged, then it would be interesting to know whether Wayfire detects it should have focus (but for this you'd have to dig in the code, xwayland unmanaged views have their own impl in `src/view/xwayland/...`. And if it should have focus, it then becomes interesting why Wayfire doesn't give it focus - you could then take a look at whether the unmanaged view is focused when it is mapped in the code.

PS. when you write in IRC, when you disconnect, I cannot answer your questions ... So it would be better to either find a permanent IRC connection, or maybe try the matrix channel.

**Comment by EoceneMiacid** [comment]
@EoceneMiacid If this problem has started occurring recently, you could bisect to see which commit has happened recently.

AFAIK it's always had this issue, and it's not as if these problems are obscure edge cases, all three apps have millions of users, surely you can quickly install either from a repo and observe the problem?

And about Matrix, you should seriously consider moving to Discord. It would hugely benefit Wayfire's development.

**Comment by ammen99** [comment]
@EoceneMiacid I don't doubt the problem can be easily reproduced, but as you can see, there are many open issues. I cannot fix all of them at once - therefore if people can gather more info and ideally figure out the actual problem, a fix will happen much more quickly.

About discord, I'm not using it too much, but I'll consider using a matrix <-> discord bridge.

**Comment by EoceneMiacid** [comment]
> @EoceneMiacid I don't doubt the problem can be easily reproduced, but as you can see, there are many open issues. I cannot fix all of them at once - therefore if people can gather more info and ideally figure out the actual problem, a fix will happen much more quickly.

Of course, I understand, you don't owe nobody your free time. I'll gladly help if i can, but in this case I can't do much more than observe and report the problem (save for diving into Wayfire's codebase and learning wlroots, but this is something I can't afford at the moment. I'm involved in too many projects already).
 
> About discord, I'm not using it too much, but I'll consider using a matrix <-> discord bridge.

That would be a start.

**Comment by EoceneMiacid** [comment]
FYI, I received some Wayland and Blender updates just now (I'm on Arch), and the Blender file dialog now appears to work correcly.

**Comment by EoceneMiacid** [comment]
The gimp dialog issues appear to be resolved as well, they now have proper focus and behave llike they should.

**Comment by ammen99** [comment]
Hmm, could this have been a bug in the applications/GTK then?

**Comment by EoceneMiacid** [comment]
I am not sure, but I'm happy it works now.

**Comment by ammen99** [comment]
Gimp dialogs seem to work here as well, it might have been a GTK issue, closing. Feel free to reopen if the issue comes back again.
