### ISSUE TITLE
grid plugin's animation leaves damage artifacts behind

### ISSUE THREAD

**Issue by mntmn** [WayfireWM/wayfire#1886]
**Describe the bug**

When tiling windows to the left or right screen half with the "grid" plugin (super+cursor keys) quickly, and animation is enabled (default, or sth like duration = 100), often undamaged areas are left behind, which flicker on subsequent compositor page flips.

Sceenshot below.

**To Reproduce**

1. Enable plugin "grid"
2. Tile window to left or right with super+left/right cursor

**Screenshots or stacktrace**
 
![Screenshot](http://dump.mntmn.com/screenshot-2023-09-04-17-53-28.png)

**Wayfire version**

`0.8.0-ea075201 (Sep  4 2023, branch 'master')`

**Comment by ammen99** [comment]
I cannot reproduce. Can you share your full config?

**Comment by ammen99** [comment]
Nevermind, I figured out how to reproduce ...

**Comment by ammen99** [comment]
This was an interesting bug to track actually, took me around 2 hours to figure out how to reliably reproduce it ;) And it turns out the problem was in core and almost completely unrelated to grid ..

Fix is 32388f7831c8f95c306971fd5645155050fd807c
[Reliable reproduction demo](https://github.com/ammen99/wayfire-tests/commit/6b6d1b489949d5c1f16c65b96fb2cee318ef1753) - basically, this can be reproduced with every transformer which changes the window size ..
