### ISSUE TITLE
scale: cannot select always on top view with the mouse

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wayfire#1927]
**Describe the bug**
As the title says

**To Reproduce**
1. Enable the WM-actions plugin and set a view to be always on top
2. Start scale
3. Click on the view from step #1
4. Nothing happens. The view can still be selected with the keyboard (arrow keys + enter)

**Expected behavior**
Clicking on a view selects it

**Screenshots or stacktrace**

**Wayfire version**
latest git

**Comment by ammen99** [comment]
I believe the problem is this function: https://github.com/WayfireWM/wayfire/blob/95ce6ddf662b27a681544f70b66c62c26dca289e/plugins/scale/scale.hpp#L9

It only searches for views in the wset node itself, but always-on-top views are in the TOP layer, not in the workspace node itself (even though they are part of the workspace set).

I'll open a PR with a fix soon.

**Comment by ammen99** [comment]
Wayfire #1928
