### ISSUE TITLE
No focus to opened application if it's placed on another workspace

### ISSUE THREAD

**Issue by stefonarch** [WayfireWM/wayfire#1946]
If there are window rules for applications to assign a workspace the application opens but doesn't get focus.

**To Reproduce**
1. Assign a workspace to app x
2. Go to another workspace
3. Open x
4. You have to switch manually to the workspace and focus it

**Expected behavior**

When opening an app it should get focus always.

**Wayfire version**
0.8.0

**Comment by ammen99** [comment]
So the expectation here is that Wayfire also switches to another workspace because the new window is assigned to this other workspace?

**Comment by stefonarch** [comment]
Exactly.

**Comment by ammen99** [comment]
This can be done with an IPC script (starting an app on a particular workspace, you can for ex. switch to the workspace and then start the app). I am not quite sure it makes sense to immediately switch to the workspace because for example if we're speaking about start-up, maybe the user wants to create a setup where they have windows all over the place, and Wayfire would just start jumping around the workspaces ... which is probably not what is wanted in that case.
