### ISSUE TITLE
Is output->scale != 1.0 supposed to make everything blurry?

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#1959]
With
```
[output:eDP-1]
mode = 2560x1600@120.000999
position = 0,0
transform = normal
scale = 1.0
```

Everything looks crisp and clean.

However when I set scale to anything different, i.e. 1.25, everything becomes blurry.

That applies to e.g. fonts in Firefox and the XFCE terminal application.

**Comment by ammen99** [comment]
This will happen with any Xwayland application, and wayland-native applications which do not support scaling. Is Firefox running as a wayland-native app?

**Comment by ammen99** [comment]
Possibly related: #599, #1180

**Comment by birdie-github** [comment]
XWayland is not installed here.

**Comment by ammen99** [comment]
Just tried with Firefox but I am not getting any issues .. Do you maybe use blur or another special effects plugin?

**Comment by birdie-github** [comment]
In XFCE4 Terminal I use bitmap fonts (Terminal) which could explain the issue.

Here's my entire config:

[wayfire.zip](https://github.com/WayfireWM/wayfire/files/12915651/wayfire.zip)

I have most such plugins disabled. I'll attach screenshots a bit later.

**Comment by ammen99** [comment]
> In XFCE4 Terminal I use bitmap fonts (Terminal) which could explain the issue.

I am not very familiar with bitmap fonts, but what I could find via quick googling definitely would explain the problem. You need scalable fonts for the scaling option to work. Or the terminal needs special support - for example in wf-panel, when a scaling option is set, we load higher-resolution icons.

I tried firefox with your config file (only changed the output name to match my output), but I failed to reproduce the issue. My guess would be that you either configured firefox to also use the bitmap font, or firefox is missing something it needs for proper scaling of its fonts (maybe a gtk portal or something similar to [this issue](https://github.com/flatpak/xdg-desktop-portal/issues/642)? But I am not sure whether this is the issue here.)
