### ISSUE TITLE
Command output is lost

### ISSUE THREAD

**Issue by lilydjwg** [WayfireWM/wayfire#1973]
It's very helpful to see what goes wrong when commands spawned from wayfire fails in some way, but wayfire currently discards their output:

https://github.com/WayfireWM/wayfire/blob/ada3a6ba2176134dc084cf373a38cd3521c1996d/src/core/core.cpp#L394-L399

I'm using lightdm and all output from the compositor is saved in `~/.xsession-errors`.

**Comment by lilydjwg** [comment]
> logs will get full with random errors

Not that full actually. Even KDE users get their logs into systemd journal. Wayfire users tend to have less applications running and the logs are much less. I have uptime near 10 days now, and `~/.xsession-errors` is only 4.8M, most of which are debugging logs from wayfire itself (perhaps mainly added by me).

> You can always redirect the output to a log file

But then I need to use one log file per command. I don't want to invent my own log daemon.

**Comment by ammen99** [comment]
Maybe we can add an option for this, because I definitely prefer the current behavior. What the default is, I am not sure - maybe we could follow the rest of the DEs and output to the log by default. PRs welcome :) (option could be called `workarounds/disable_command_output_in_logs` or something more fitting if you can think of a better name)

**Comment by lilydjwg** [comment]
Yes, that's what I'm thinking too. I don't care much about the default behavior since I'm going to configure Wayfire after all. I'll try to come up with a patch.
