### ISSUE TITLE
Built-in FPS monitor

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wayfire#2040]
Would be great to have it if it makes any sense.

I'd love to see an FPS counter for the active application, or Wayfire itself if it's the only running GUI application.

Would be great to be able to configure its font face, font size, placement and opacity.

**Comment by soreau** [comment]
You could write a plugin to do this, maybe look at [bench plugin](https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/bench.cpp) for starters.

**Comment by ammen99** [comment]
If you have a single OpenGL application running (for example fullscreen game or something) the output of the bench plugin (depending on how you configure it) will be more or less equal to the FPS of that client, because Wayfire redraws only when the clients update.

Otherwise, you'd want to track how often clients submit a new buffer, but I don't think such a plugin is that useful upstream.
