### ISSUE TITLE
Can't switch workspaces without moving background or bar

### ISSUE THREAD

**Issue by hey2022** [WayfireWM/wayfire#2146]
**Describe the bug**
When switching workspaces with the viewport switcher plugin, my wallpaper (swww) and my bar (waybar) moves as well. Also, I can't get it to work like in the showcase with wf-background.

**To Reproduce**
1. Enable vswitch plugin
2. Try to switch workspaces
3. The bar and wallpaper moves as well

**Expected behavior**
Only the windows change, but the bar and wallpaper doesn't move.
Like in the [showcase](https://www.youtube.com/watch?v=QqbjNhIz1nI) for the Vswitch plugin, the background doesn't move when switching workspaces.

**Wayfire version**
0.8.0-1d6ab59 (Jan 19 2024, branch 'master')

**Comment by ammen99** [comment]
The animation of vswitch has changed since the video was made, and now there is no way to get the old animation (the new animation has the benefit of showing you a visual indication even switching between empty workspaces).

There are also no plans to bring the old animation back, but you (or whoever is interested) can re-implement the old vswitch as a plugin.
