### ISSUE TITLE
Enabling/disabling output via DPMS will duplicate mouse cursors when using multi monitors.

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2147]
The title describes the issue that affects the output layout and results in duplicated mouse cursors. This means you will get two identical mouse cursors, one for each screen instead of just one cursor for all screens, also duplicating the cursor movement.

wlr-randr --output DP-1 --off ; wlr-randr --output DP-1 --on

To quick fix the output layout issue, you need to power off/on the output using the power button.

**Comment by ammen99** [comment]
What happens is that the client sets both output's coordinates to `0,0`: so, you get a duplicate cursor. An easy way to fix this is to specify the position when re-enabling the output with wlr-randr, or using [wlopm](https://sr.ht/~leon_plickat/wlopm/) for power management instead of fully disabling the output.
