### ISSUE TITLE
Introduce sets of 2D workspaces

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wayfire#217]
I just had an idea that we can have multiple sets of 2D workspaces, which could then be moved between outputs.

This can even be made a plugin, so in theory very little (or none) core changes would be needed.

**Comment by ammen99** [comment]
On a second thought, doesn't look too useful, and doesn't fit with the main plugins anyway.

**Comment by ammen99** [comment]
On a third thought, this makes sense. This can be a solution to saving and restoring output state on unplug and replug, moving whole workspace sets between outputs (kinda what [this plugin](https://github.com/ammen99/wayfire-plugins/blob/master/src/primary-monitor-switch.cpp) attempts to do)

It is also the way to provide independent workspaces without special-casing everywhere (#977) - instead of using workspaces, a plugin who wants to provide independent workspaces can just use different workspace sets with a single workspace.

The implementation might be a bit tricky, and will potentially require splitting the current `workspace_manager` into `workspace_set` and a manager.

**Comment by Javyre** [comment]
@ammen99 How would you see plugins dealing with workspace sets moving from one output to another? Would it be on a view-by-view basis that it should accept the incoming views on the output still? This would break tiling layouts on the workspace sets for example. Or should the plugin instances be by workspace set now instead of by output?

**Comment by ammen99** [comment]
Plugins will be free to store their data on the workspace set or per output, depending on how they want to operate.
