### ISSUE TITLE
Do not tile views with min==max size

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2243]
to reproduce the issue you must have a small dialog
open 6 views with dialog included, have the simple tile enabled, close any view except the dialog, then the dialog will get this weird aspect ratio

![nice](https://github.com/WayfireWM/wayfire/assets/24453/1acd9669-6411-40bb-990a-6a2dc536bed2)

**Comment by ammen99** [comment]
This is pretty much expected behavior here, if a view is tiled but cannot be resized to fit (for example because the client refuses to resize itself) it will be stretched to fit the space for it. 

I think that probably what Wayfire is missing is the hints for min and max size. If a view has min == max size, it should not be tiled, I expect this is how this dialog works in Sway and Hyprland.
