### ISSUE TITLE
XWayland windows unmaximized on idle screen

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wayfire#227]
If there is an XWayland window currently maximized and you go idle for some time and the screen goes blank and after awakening the XWayland screen is shifted down and right by quite a bit.

This issue does not happen with wayland native windows.

**Comment by ammen99** [comment]
What is the "Xwayland screen"? Do you mean all Xwayland applications?

**Comment by epsilon-0** [comment]
Yes, thats what I meant. The XWayland windows get shifted.

**Comment by ammen99** [comment]
Does that still happen?

**Comment by epsilon-0** [comment]
This still happens (though i've only tested with kitty)

**Comment by ammen99** [comment]
@epsilon-0 Do you use the autorotate-iio plugin by some chance? Also, which version of Xwayland are you using? Could this happen because you are for ex. unplugging an output?

I am asking since actually the idle timeout shouldn't have any effect on window positions or such whatsover. I'm not even sure whether Xwayland is even aware that this happens.
