### ISSUE TITLE
Allow IPC clients to query and temporarily set config options

### ISSUE THREAD

**Issue by killown** [WayfireWM/wayfire#2323]
Actually, you can obtain the location of the wayfire.ini file by examining the log file. However, the challenge lies in knowing the location of the log file, as the wayfire command does not provide any hints about it. It would be helpful to have a IPC method that returns the configuration file used by the wayfire session, and the location of the log file as well.

In a practical scenario, let's say we have a project where we need to retrieve wayfire information from the configuration file. Since there is no IPC method available that returns the animation speed from scale, one use case could involve parsing the configuration file and extracting the relevant information which you can't obtain from IPC methods

**Comment by ammen99** [comment]
There is no way to obtain the log file from Wayfire, because Wayfire's log is stdout. Stdout might be redirected to a file, but that is something which happens outside of Wayfire (so Wayfire can't know where the user decided to redirect stdout).

About the config file, it is already made available as an environment variable: https://github.com/WayfireWM/wayfire/blob/master/src/default-config-backend.cpp#L111

That is of course if you're using the default config backend. Other config backends (for example earlier there was a gsettings backend) you won't get this env var because there is no config file.

In general I think it could be useful to allow IPC clients to get and set config options with an IPC method, but that is not implemented yet.

**Comment by killown** [comment]
forgot to check env vars, WAYFIRE_CONFIG_FILE is enough
