### ISSUE TITLE
give an option to run wayfire as root

### ISSUE THREAD

**Issue by rizalmart** [WayfireWM/wayfire#2540]
Give an option to run wayfire on root account by simply adding a command line parameter just like in Hyprland's "--i-am-not-stupid" parameter for running Hyprland on root.

**Comment by soreau** [comment]
Completely untested, but does [this patch](https://termbin.com/ysq0f) work? The expected usage is `# wayfire --with-great-power-comes-great-responsibility`.

**Comment by rizalmart** [comment]
> Completely untested, but does [this patch](https://termbin.com/4zhp) work? The expected usage is `# wayfire --with-great-power-comes-great-responsibility`.

i wonder why this patch doesn't merged?

**Comment by soreau** [comment]
For one thing, it hasn't been tested. Another thing is that the reasoning behind it is questionable, since it can make the system more vulnerable to exploits. Also, you should probably not run as root unless you know why you need to. Running the display server means every process it spawns runs as root, and this is not how the system was designed to use. Finally, I think this is something easy enough to hack in a patch, if they want this behavior on their machine alone, and shouldn't be available in i.e. stock distro packages.
