### ISSUE TITLE
Blur flickering on default settings in any app

### ISSUE THREAD

**Issue by Malmik** [WayfireWM/wayfire#272]
Laptop: Lenovo Ideapad s130
OS: Arch Linux 64bit

https://streamable.com/5h1mm

I know quality is very bad, but the problem is visible.
The first part is with opacity set to 1.0, the second part is with teminal's opacity set to 0.6.

**Comment by soreau** [comment]
This works fine for me here with radeonsi driver on polaris11. Can you test if this happens with weston-simple-egl? The weston demo binaries should work in wayfire. I'm wondering if this is triggered because the application is gl-accelerated and combined with the wayfire blur shader, is tripping up the driver somehow.

You might also check if this happens with different versions of mesa, be it latest or older versions.

**Comment by ammen99** [comment]
@Malmik I think it might be simply your blur settings, can you tell me what your settings for blur are?

**Comment by soreau** [comment]
...or just try the defaults (no blur settings) I hadn't considered blur settings but this is a certain possibility.

**Comment by ammen99** [comment]
More specifically, if you have a "low" number of iterations and "high" degrade or offset, this might be the visual result. Sadly I can't tell you what are the good values, you'll have to experiment to find settings which you like.

**Comment by Malmik** [comment]
Hi!, sorry for very late response.
My blur settings are:
mode = normal
kawase_offset = 2
kawase_degrade = 3
kawase_iterations = 3

Thing i have realised is that blur works improperly only when wallpaper is underlying. When thing below is another apllication window, blur works okey.

**Comment by soreau** [comment]
@Malmik These options work fine here, without problem. Does the same happen without specifying any kawase_* settings? Does the same happen if you enable alpha plugin and use Alt+Scroll to adjust alpha on any other window?

**Comment by Malmik** [comment]
I had alpha plugin enabled all the time. When I disabled kawase options it works good. I have intel i915 integrated gpu

**Comment by Malmik** [comment]
But with enabled kawase, even alt scroll is not working

**Comment by soreau** [comment]
> But with enabled kawase, even alt scroll is not working

What is not working about it? It doesn't make the window transparent or it does but the blur has the bug in the video?

Since the same settings work here with radeonsi, I'm inclined to believe this might be a driver bug.

Can you try other methods for blur? You can use `method = gaussian` or `method = box`. There is also `bokeh`, but it uses a bit more resources.

**Comment by ammen99** [comment]
@Malmik looking at your config, you have `degrade = 3` but `iterations = 3` too. You'd have to either lower degrade or increase iterations.

**Comment by ammen99** [comment]
Also forgot to mention, you say that the bug happens only in some cases depending on what's behind the window. This is pretty normal, because it is caused by instabilities when calculating the blur (so it depends on what we're blurring).

**Comment by Malmik** [comment]
@soreau the blurr is buggy

**Comment by ammen99** [comment]
@Malmik what happens if you tweak the settings a bit?

**Comment by Malmik** [comment]
@ammen99 incrasing iterations to 4 does no difference

**Comment by soreau** [comment]
@Malmik Try kawase_degrade = 1.

**Comment by soreau** [comment]
@Malmik Try this combination:

kawase_offset = 3
kawase_degrade = 1
kawase_iterations = 5

**Comment by Malmik** [comment]
Thanks soreau! It works now :)

**Comment by ammen99** [comment]
A note for people experiencing the same: Having such a high degrade means that a much higher number of iterations is needed. Otherwise blur is unstable and such flickering occurs.
