### ISSUE TITLE
Touchscreen gesture recognition does not release touch points in the clients

### ISSUE THREAD

**Issue by myfreeweb** [WayfireWM/wayfire#290]
On Sway, I can press and release >2 fingers on the touchscreen in gtk3-demo's touch demo just fine.

On Wayfire, the third touch gets stuck :(

**Comment by myfreeweb** [comment]
hm, all the `touch_notify` stuff is happening through focus o_0

**Comment by myfreeweb** [comment]
I've been thinking it's because of the gesture recognizer. Finally got around to trying to disable it, and yes:

```diff
diff --git i/src/core/seat/touch.cpp w/src/core/seat/touch.cpp
index 093e13e..b2da587 100644
--- i/src/core/seat/touch.cpp
+++ w/src/core/seat/touch.cpp
@@ -193,8 +193,8 @@ void wf_gesture_recognizer::register_touch(int time, int id, wf_pointf point)
     if (in_gesture)
         reset_gesture();
 
-    if (current.size() >= MIN_FINGERS && !in_gesture)
-        start_new_gesture();
+    // if (current.size() >= MIN_FINGERS && !in_gesture)
+    //     start_new_gesture();
 
     if (!in_gesture)
     {
```

^^ fixes the problem.

**Comment by ammen99** [comment]
Yeah this is certainly a problem there. The current system is the following:

1. Touch points are taken and forwarded to the client
2. User presses 3rd touch point. At this point, the client should be notified that all touch points are "up" because we have a gesture
3. Do whatever is needed with touchpoints to calculate the actual gesture.

I guess in 2. I somehow forget to send one "up" point.

**Comment by myfreeweb** [comment]
Ideally we shouldn't "have a gesture" immediately after the 3rd touch point, only when the algorithm has detected that an actual gesture is going on (via the `MIN_*_DISTANCE`s)… I'd prefer full multi-touch in apps to work. I don't currently have any useful (i.e. not touch event demo) apps that *actually* need `>2` fingers :D but still.
