### ISSUE TITLE
Foreign toplevel visibility signal

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wayfire#293]
My panel needs to know if there is a maximized window on the current workspace (if so, it'll go opaque).

I intended to use foreign_toplevel for this, but I am not told if the window is on the current workspace or not. In other words, my panel just knows that there is a maximized window on some workspace, but it doesn't know if any part of this window is visible.

A few possible solutions:
1. Wayfire implements a custom wlr_foreign_toplevel with an extra `visible` state. I don't particularly like this because technically wf will be out-of-spec
2. Wayfire has a special protocol that extends foreign_toplevel and sends just that bit of extra info. This is good because it is extensible and is ostensibly the cleanest solution (save for wlroots upstream adopting something)
3. Wayfire has a special protocol who's only job is to tell panels to go opaque or not. I can probably implement this out-of-tree if it comes to it.
4. Wayfire doesn't send the maximized state if the window isn't on screen. As far as the panel will be concerned, the window won't be maximized. This should either be opt-in via layer-shell namespace (like `$unfocus`) or  via the hacks section in the config file.

**Comment by ammen99** [comment]
Gonna close this one because this is not something wayfire is supposed to do itself. The right way forward would be:

1. wlr-workspaces needs to be merged into wayland-protocols
2. foreign-toplevel needs to be merged into wayland-protocols
3. foreign-toplevel needs to be adjusted with the event

Obviously, these steps depend on external factors so I cannot give any ETA. A custom protocol would probably be the easiest solution if you need this right now.
