### ISSUE TITLE
wayfire not starting

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#327]
![IMG_20191103_165016](https://user-images.githubusercontent.com/44837339/68084313-0a84c400-fe2c-11e9-925e-3297f7e9eebd.jpg)

here is the camera pic.

this happens when using wlroots-git
and wayfire-git

**Comment by librewish** [comment]
also another thing 
this is from wayfire 0.3 it happens when trying to close xwayland window using exit button

segmentation fault (core dumped) wayfirerender-manager.cpp:419] constant_redraw_counter got below 0!rs(4 vs 0!)ence 172, value 0

**Comment by ammen99** [comment]
Is the problem still present?

**Comment by dikeert** [comment]
@ammen99 For me it shows gray screen and then, as soon as I try to move mouse, it disappeares and that's it. It ignores all of the hotkeys, nothing's happening.

**Comment by ammen99** [comment]
What version of wayfire and wf-shell have you installed @dikeert ?

**Comment by dikeert** [comment]
Ok, I've installed the wf-shell and it starts now. It still ignores all of the keyboard shortcuts though. Version if 0.4.0

**Comment by dikeert** [comment]
I gotta get some sleep, so I'll probably answer tomorrow.

**Comment by ammen99** [comment]
@dikeert How did you install Wayfire? Btw you should join #wayfire on freenode, it is the best place for  longer discussions on how to debug installation problems.

**Comment by dikeert** [comment]
@ammen99 Hello!

Sorry for delay.

It is all sorted now. Apparently, I have to copy config into config directory first. Before that it was starting like there were no settings. Also I didn't have wl-shell installed. Once I've put the config into place and installed wl-shell, everything became normal.

This is somewhat unusual behavior though. Usually, software that have their configs in /usr/share/doc/$package uses those configs as defaults. That's why I didn't bother at first to copy the config.

Hope it help.

**Comment by ammen99** [comment]
dikeert, Wayfire 0.4 should be able to start without a config file, that's why I was asking which version you have tried. If you have time, I'd like to debug why it doesn't work without a config file (but please join the IRC channel)

**Comment by ammen99** [comment]
After discussion on IRC, the problem was that wf-shell wasn't installed, after that, Wayfire starts successfully, even when command bindings from the default config file are not available (but there is wf-panel, so the user can launch a terminal from there and add/edit their config file)
