### ISSUE TITLE
Window enters wobble state after using fast-switcher

### ISSUE THREAD

**Issue by Clyybber** [WayfireWM/wayfire#351]
To reproduce enable fast-switcher and grid and enable wobble but disable wobble for grid.
Then start wayfire > open an application > use fast-switcher > use grid
=> the window will wobble

**Comment by ammen99** [comment]
After a bit of debugging on IRC this happens because the fast-switcher modifier was being still being held when the attempt to use grid was made.

Here are a few things to make the situation better:

1. For fast-switcher, if any key other than the bound key is pressed, just exit fast-switcher even if the mod is still being held.
2. In grid, if plugin activation fails, don't fall back to "wobbly" but to "none" as animation.

**Comment by soreau** [comment]
From my tests, this is no longer an issue with latest wayfire.
