### ISSUE TITLE
Allow activating Expo plugin while Move plugin is active

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#404]
Currently, it is the other way around: we press and release the modifier key to expose workspaces and grab the window to send it.

**Comment by ammen99** [comment]
I can see that this would be kind of cool, but to be honest, why can't you activate Expo first and then grab the window?

**Comment by AdrianVovk** [comment]
@ammen99 it's the kind of UX quirk that makes software feel really polished when/if the user discovers it.

Also, if you do come up with a way to do this, maybe there could be some standard way to pass signals around so that maybe something like vswipe and my custom overview can interact (it's a pipe dream, I know)

**Comment by ammen99** [comment]
There is a standard way to pass signals around, and some plugins are already using it (wobbly, grid, move)

This is possible to implement, however it would mean that we have to somehow hardcode the fact that expo can be activated while move is active...

**Comment by ammen99** [comment]
I thought about this once more, and sorry, not gonna happen. This requires way too much special casing on both move and expo's side.

Anyway, I believe this feature would be useful if you want to grab a view and move it to an adjacent workspace. #651 lets you do that, you can grab the view, move to the screen edge, after a bit the workspace will be switched while the view is still grabbed.
