### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#473]
memory leak is exclusive to wayfire - sway is not affected.
Wayfire 0.4.0

1. Open a terminal
2. killall wf-panel
3. wf-panel
4. repeat 2 & 3 a couple of times

The memory usage of wayfire will increase each time by 5-10Mb. (have reached 600Mb)
Note that this affects only created surfaces that use layer shell somehow.

**Comment by myfreeweb** [comment]
couldn't reproduce with [`gtk-layer-demo`](https://github.com/wmww/gtk-layer-shell), relaunching several times and fiddling around with settings each time. RSS increased a bit but heaptrack doesn't show any significant consumption growth, and nearly all the "leaks" it finds are from shader compilation, searching for "layer" only shows a couple kilobytes

![heap-wf-lsh-consumed-fs8](https://user-images.githubusercontent.com/208340/79223313-c4637000-7e61-11ea-808d-8a7ab21c1a24.png)
![heap-wf-lsh-fs8](https://user-images.githubusercontent.com/208340/79223436-0096d080-7e62-11ea-8f0a-9f8ad234f38a.png)

> sway is not affected

Did you try *wf-panel* in sway? Other layer-shell things in Wayfire?

**Comment by soreau** [comment]
Maybe a particular panel widget is causing this like window-list?

**Comment by damianatorrpm** [comment]
I rebooted the machine and I thought that the problem is gone.
restarting wf-panel no longer sees this ram increase,
but now most Qt applications do.

No memory leak can be seen if the Qt applications are started from cmd
with 
> QT_QPA_PLATFORM=wayland

So it may be related to xwayland or to the actual server side decoration which is rendered for Qt xwayland windows.

**Comment by ammen99** [comment]
Once myfreeweb found the root cause, I can now also explain why Waybar and wf-panel both cause the memory leak on my computer, while gtk-layer-demo doesn't. It is simple, wf-panel and Waybar cause the workarea to change because they have exclusive zones. This triggers a resize of my terminal, which contains buttons, which in turn are destroyed and allocated again ... On the other side, gtk-layer-demo does not have any exclusive zone set by default so that's why it also doesn't trigger a memory leak.
