### ISSUE TITLE
can't see half of the window

### ISSUE THREAD

**Issue by linuxuser1337** [WayfireWM/wayfire#485]
I installed wayfire.
I have 2 monitors, when moving window from monitor 1 to monitor 2
half of the window is always hidden when window is on monitor 1 and monitor 2.
While moving it shows window correct.

**Comment by ammen99** [comment]
This is the expected behavior. Monitors are meant to be independent, and this introduces a ton of corner-cases and potentially unwanted behavior if a window is visible on multiple monitors at the same time.

Note it should be possible to make Wayfire display the view on both outputs with a plugin (the move plugin does it already), however there are no plans to support such a feature officially for the aforementioned reasons.
