### ISSUE TITLE
nested wayfire on x starts with empty screen

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#494]
On X11 if run wayfire the nested wlroots-x11 window shows up.
The screen is black until with <ctrl> + <alt> + drag one triggers the cube plugin.
(does not react on mouse click or key press into black window etc)

EDIT: wayfire nested on wayland does not start up at all
gnome-shell used as host wayland-server in both cases

**Comment by ammen99** [comment]
Have you tried running Sway or another wlroots compositor? Do they work?

**Comment by damianatorrpm** [comment]
sway work properly works nested on x11
sway does not work nested on wayland
wayfire, wlroots. sway (latest git)

**Comment by ammen99** [comment]
There is also the problem that GTK apps like the panel and the background may try to start on GNOME itself and not in the nested wayfire (which is gnome's problem). Also, you indicated that Wayfire responds via cube so I'd say wayfire X11 backend works and it is GTK playing tricks again.

For Wayland, I suggest opening issue on wlroots, seems like the problem is not on our side if it doesn't work for Sway either.
