### ISSUE TITLE
xkb_variant ignored in command bindings

### ISSUE THREAD

**Issue by l3nkz** [WayfireWM/wayfire#498]
I use a german keyboard layout variant called 'neo'. I have the following in my config:
```
[input]
xkb_layout = de
xkb_variant = neo
```
Inside windows the keyboard variant is properly working. However, it doesn't work for any of the wayfire global keybindigs. As far as I can tell, the default variant (qwertz) is used.

**Comment by l3nkz** [comment]
I looked in the code and compared it to how sway handles key bindings and the problem seems, that wayfire "only" uses the keycodes which correspond to the actual key on the keyboard. Sway also supports using "translated" keysyms which apparently are translated (by xkb) keycodes with respected xkb_variant. Now, since the keyboard bindings are defined using the KEY_ syntax, I am not sure whether this is actually the expected behavior or not?
Maybe we add a binding_keysym or something like this? Is something like this wanted at all?

**Comment by ammen99** [comment]
Oh, I thought it is not working for clients (which would be interesting since I am using multiple languages and variants myself).

Anyway, this is the expected behavior, Wayfire does not support bindings in arbitrary languages, only the raw keycodes are considered. This ensures consistent keybindings regardless of current language. Obviously, you can write a custom plugin which feeds all keys to its own xkb_state and then triggers different actions, but this is not something I want upstream.
