### ISSUE TITLE
No resize cursor on server decorated windows on a scaled output

### ISSUE THREAD

**Issue by solarkraft** [WayfireWM/wayfire#509]
Hi! I like Wayfire quite a lot and am quite happy it exists. It's surprisingly polished!
Even how well fractional scaling works baffled me, but something distracting from that a little is that on server side decorated resize cursors don't appear when the display is set to any scaling factor other than 1 (including 2). 

I'm on 0.4.0-e32dba2. It works perfectly on GNOME and KDE client side decorated windows. Resizing also still works.

**Comment by ammen99** [comment]
Ha, thanks for this bug report. Indeed, wayfire is not loading cursors for scales other than 1, although I assumed wlroots will do so behind the scenes(but it doesn't). Can you check whether http://ix.io/2lPy fixes the issue?

I also suspect #239 is the same problem. I recall that @AdrianVovk was using Wayfire with scale=2, so that's why cursors don't work for him as well.

**Comment by soreau** [comment]
> Can you check whether http://ix.io/2lPy fixes the issue?

It fixes cursor on black border of force-fullscreened view on scaled outputs here.
