### ISSUE TITLE
xwayland drag icons are stuck on one output

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#515]
When dragging a chrome tab onto another output it is not visible on the non primary yet output,
even while moving.

**Comment by ammen99** [comment]
These are not views handled by the move plugin, but xwayland override-redirect views. Wlroots does not support Xwayland DnD very well, see https://github.com/swaywm/wlroots/pull/841

We could make core move OR views to an appropriate output, which still has some drawbacks - such views will continue to be visible on a single output, and determining the best output is not trivial.

**Comment by ammen99** [comment]
Another idea: we can match Xwayland DnD icons via their window-type and emulate the behavior of a drag icon. Should be relatively easy.

We should also probably expose the DnD icon API to plugins, and allow multiple drag icons.

**Comment by ammen99** [comment]
> When dragging a chrome tab onto another output it is not visible on the non primary yet output,
> even while moving.

I tried to fix the issue, but it is not as easy to fix as I hoped. Chrome does not use drag icons when dragging tabs - instead, it creates normal windows and relies on being able to move them around freely (which Wayfire does not allow right now). So, this issue is a wont-fix.

I have added a PR for basic xwayland drag-and-drop icons (#1014) which works for real drag-and-drop operations: for example, I could drag and drop text from Xwayland chrome to Xwayland gedit. I am still unsure whether this approach is worth pursuing, because:

- as seen in this issue, not all drag-and-drop problems in Xwayland are solved
- drag and drop does not work between Xwayland and Wayland clients, even if the drag icon shows above Wayland clients.

Anyway, I figured you might still prefer to test the PR, and if you think it is a real improvement, we could merge it.
