### ISSUE TITLE
Keep windows above or below

### ISSUE THREAD

**Issue by BenWestcott** [WayfireWM/wayfire#554]
It would be handy to be able to make certain windows stay always at the top or bottom of the window stack. The most useful would be to have it controlled for the currently focused window by a key combination, but it would also be nice to have it automatically apply to certain windows.

In addition to being a generally useful tool, I'm also interested in the ability of such a feature to make custom shells, using keep below for the desktop background and keep above for any panels or docks.

**Comment by ammen99** [comment]
Keep always above is kind of implemented, but I may have forgotten to add it to the documentation: https://github.com/WayfireWM/wayfire/blob/master/metadata/wm-actions.xml

About desktop background and such things - I believe this would be the wrong approach. What kind of panels and docks are you speaking about? If you are writing a panel/dock/whatever, it is highly recommended to use the layer-shell protocol. It is supported by wayfire, sway and many others, and using it  the app itself can indicate what type it is (i.e background, panel, etc.).

**Comment by BenWestcott** [comment]
Interesting, I'll play with that a bit.
And yes, it would be the hacky way instead of the proper way, but I'm not developing the software involved. So I think hacky would work well enough.
Particularly I'm referring to LXDE. The developers are (understandably) reluctant to use compositor-specific APIs, so I figured it could be done well enough on the other side, and be a useful general-purpose tool too.

**Comment by ammen99** [comment]
The protocol I mentioned is the closest thing there is to cross-compositor protocol (it is not limited to Wayfire - there is/was experimental implementation for weston, Sway and other wlroots compositors also use it).

By the way - using a panel from LXDE without porting it to wayland will probably not be worth it:
1. You cannot use a window list because pure Wayland clients will not be visible (there is a wayland protocol for that though)
2. Same thing for workspaces - there is a planned protocol for that, but again, it needs to be used by the panel.
3. Positioning - Wayfire currently has independent outputs, and generally any application started is launched on the currently focused monitor, even X11 apps that try to position themselves elsewhere. Hence, in a multi-monitor layout, the panel (except if it doesn't set the override-redirect flag) won't be able to appear on the monitor it wants to be. There is of course exception for layer-shell clients.

As usual, YMMV - if you have a single output, without window and workspace list - then this could probably work. If you want to go ahead with that approach (I don't recommend), take a look at https://github.com/WayfireWM/wayfire-plugins-extra/blob/master/src/background-view.cpp
This is a plugin developed by @soreau which you can use to put a random client as a background. It should be trivial to make it support panels as well (on top).

**Comment by BenWestcott** [comment]
I did adapt background-view to work for panels, however both tools (background-view and wm-actions) apply on a per-process basis rather than a per-window basis. It seems like the only alternative would be to match to a window by its title, and I tried to build a plugin that did that, but I was having trouble grabbing the window list. The panel and desktop probably don't set window names anyway though.
I suppose it does have to be done client-side to a reasonable extent. I've attached the relevant files though in case anyone else is interested in toying around with this.
[foreground-view.tar.gz](https://github.com/WayfireWM/wayfire/files/4755691/foreground-view.tar.gz)
