### ISSUE TITLE
Preserve window states on monitor changes

### ISSUE THREAD

**Issue by alexherbo2** [WayfireWM/wayfire#593]
**Scenario**

Keep the window maximized and proportioned when sending a window to another monitor with a different size.

**Comment by soreau** [comment]
> **Scenario**
> 
> Keep the window {...} proportioned when sending a window to another monitor with a different size.

If the ratio between the width and height of the two outputs are the same, you can proportion the view by using the output scale option, though this can make the views blurry. [Here](http://ix.io/2rJl) is a patch to do the proportioned part, though I can't guarantee it would be accepted.

**Comment by ammen99** [comment]
> [Here](http://ix.io/2rJl) is a patch to do the proportioned part, though I can't guarantee it would be accepted.

Looks good, actually core already does things like that when moving the views from outputs which have been unplugged: https://github.com/WayfireWM/wayfire/blob/master/src/core/output-layout.cpp#L180-L194

Maybe we can move the linked block of code to `move_view_to_output`? (but add a boolean flag to that function so that this behavior can be turned off in case a plugin wants to override it). And also add the scaling there which you have. This way, we don't have to write the same logic in multiple places.
