### ISSUE TITLE
unresponsive applications causes kind of focus steal

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#663]
Not related to the sublayer focus steal.

1) gnome terminal is open
2) steam is open
3) steam is focused
4) they are positioned so that gnome-terminal is
    visible as its geometry has a lower x.y point
5) restart a resize action using steams CSD

Steam is busy and responds to the resize request with a ~3 sec delay
Meanwhile I focused gnome terminal.
3 seconds have passed and now gnome-terminal has keyboard focus,
but steam starts resizing even though left button is not pressed down,
neither does it have focus.

**Comment by ammen99** [comment]
video please? I think this might be a behavior we cannot prevent.

**Comment by ammen99** [comment]
On a second re-read, I don't think we can fix this in any way. A possible "fix" (which I think is not really wanted):

1. Start with size W,H
2. Resize to W2, H2. Resized client doesn't do anything yet because it is temporarily unresponsive
3. Release mouse button, switch focus.
4. We could say to the first client: resize back to W,H because mouse button is released and it hasn't resized yet
5. (after a few seconds) Client resizes to W2, H2 because that's the first request it received
6. (after a few more seconds) Client resizes to W,H to honor the second request

What we have now is these steps without 4. and 6. I'd argue the current behavior is better.
