### ISSUE TITLE
[xwayland] stack order is not sent to Xserver

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#666]
Iif you scroll the mousewheel on the sub-layered (keep_above) view
but it has not focus, the underlying view receives the scroll event.

e.g Maximize chrome
vlc half size of but on top
focus chrome
mousewheel on vlc => chrome scrolls

The normal behavior is that even if not focused views still act on scroll events.

**Comment by ammen99** [comment]
Can you reproduce with wayland applications?

**Comment by damianatorrpm** [comment]
wayland on wayland works correctly

**Comment by ammen99** [comment]
The problem here is that we do not adjust the Xwayland stacking order to match our own.

The correct solution:
1) emit a signal whenever the view's stacking order changes (this will need adjustment in workspace-manager)
2) the Xwayland view implementation needs to pick this up, find the next Xwayland view on top of that view and send the corresponding RestackAbove/Below X11 events (potentially add this as a function in wlroots too).

**Comment by damianatorrpm** [comment]
actually I just found out that affects xwayland views in general not just sublayered ones

**Comment by damianatorrpm** [comment]
`the Xwayland view implementation needs to pick this up, find the next Xwayland view on top of that view and send the corresponding RestackAbove/Below X11 events (potentially add this as a function in wlroots too).`

That would mean though if RestackAbove/Below is in wlroots and wayfire needs to react to setting this property,
views would need to be sublayer themselves? _NET_WM_STATE/above/below

**Comment by ammen99** [comment]
> That would mean though if RestackAbove/Below is in wlroots and wayfire needs to react to setting this property,
> views would need to be sublayer themselves? _NET_WM_STATE/above/below

This is not relevant at all. All we need is to say to Xwayland "this window is on top of the other" which is not done via properties, 
it is done with StackMode here: https://tronche.com/gui/x/xlib/window/configure.html
