### ISSUE TITLE
[blur] unnecessary blurring - performance

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#669]
So I disabled blur and was shocked how much faster everything became.
The only view with transparent background is wf-panel

What I noticed though is that the GTK applications have their window shadow blurred,
which is part of the wm_geometry but not of the view geometry AFAIK.

I don't think that the window shadow should be eligible for blur.

**Comment by soreau** [comment]
Yes it is true, blur does consume resources. The problem with only blurring the input region, is when a view is transformed, for example by wobbly. Blur only operates on rectangular areas. When wobbling, the view output_geometry encompasses the extents of the view. If you try to avoid blurring the shadow and only blurring the input region, this means you would have to somehow transform the blurred area into a non-rectangular 'wobbled' area. With X, this behavior is natural because the decorations are separate from the windows, so in e.g. compiz, this works without any extra effort.

**Comment by ammen99** [comment]
> What I noticed though is that the GTK applications have their window shadow blurred,
> which is part of the wm_geometry but not of the view geometry AFAIK.

The reverse, it is part of the bounding box but not the wm_geometry :)

**Comment by ammen99** [comment]
I believe there are only two more general blur optimizations we can do:

- [ ] don't use a transformer at all in case window_geometry == opaque_region . This would not blur shadows as @damianatorrpm suggested. Because I am not sure how well this will work with rounded corners, maybe we'll have to not blur in case opaque region is 95+% of the window geometry (which should also be fine I think).

- [ ] Don't expand damaged region in places where no blurred view is available. This would make the workspace-stream-pre logic more complex, but it would probably still be more efficient than what we currently have.

@damianatorrpm In your specific case though, there is another thing which can help (and I have been thinking this is something which will generally be needed):

- [ ] Add an option to blur only specific views with a matcher expression. This will require the second optimization from above to be really efficient.

**Comment by soreau** [comment]
> I believe there are only two more general blur optimizations we can do:
> 
>     * [ ]  don't use a transformer at all in case window_geometry == opaque_region . This would not blur shadows as @damianatorrpm suggested. Because I am not sure how well this will work with rounded corners, maybe we'll have to not blur in case opaque region is 95+% of the window geometry (which should also be fine I think).
> 

Would it be the case where some views would have shadows blurred and others not? Would this cause the possibility of blur flickering between blurring shadows and not? I don't like the idea of percentages, it just seems to me this could permit visual bugs.

**Comment by ammen99** [comment]
> > I believe there are only two more general blur optimizations we can do:
> > ```
> > * [ ]  don't use a transformer at all in case window_geometry == opaque_region . This would not blur shadows as @damianatorrpm suggested. Because I am not sure how well this will work with rounded corners, maybe we'll have to not blur in case opaque region is 95+% of the window geometry (which should also be fine I think).
> > ```
> 
> Would it be the case where some views would have shadows blurred and others not? Would this cause the possibility of blur flickering between blurring shadows and not? I don't like the idea of percentages, it just seems to me this could permit visual bugs.

better ideas :P ?

I don't think a percentage like 95% will be problematic. In practice, most apps are either wholly opaque or wholly translucent.

About blurred vs nonblurred shadows, you are right. Maybe we can limit blur to a more specific region (wm geometry only+subsurfaces)

**Comment by soreau** [comment]
> About blurred vs nonblurred shadows, you are right. Maybe we can limit blur to a more specific region (wm geometry only+subsurfaces)

I don't think we can easily limit to wm geometry for the reasons outlined in my first comment here.

**Comment by damianatorrpm** [comment]
isn't it possible to just blur if actual window contents are opaque?

**Comment by damianatorrpm** [comment]
on second thought this is a bad idea as they may change

**Comment by damianatorrpm** [comment]
I see now that it's already very optimezed, and further performance improvements may not be possible,
although I think it should be possible to not blur the window shadows from gtk as they appear sometimes more like a glow instead of shadow.

**Comment by soreau** [comment]
> I see now that it's already very optimized, and further performance improvements may not be possible,
> although I think it should be possible to not blur the window shadows from gtk as they appear sometimes more like a glow instead of shadow.

It's not really feasible to avoid blurring shadows on surfaces and still support transforms such as wobbly. This is because the way blur works. It takes the bounding box of the transformed surface and blurs whatever is behind that, and then blends the blurred background and the surface but relies on the alpha channel in the surface to blend. Since the shadow is part of the surface and the shader has no way of telling otherwise, the blurred background is blended with the shadow, rendering the effect you see.

**Comment by damianatorrpm** [comment]
is it in general possible to define black/white list for blur via window-rule-thing?
Otherwise I agree there is nothing else that can be done.

**Comment by soreau** [comment]
Yes it's possible, see [wayfire/matcher.hpp](https://github.com/WayfireWM/wayfire/blob/master/src/api/wayfire/matcher.hpp) and wf-utils for API and [animation plugin](https://github.com/WayfireWM/wayfire/blob/master/plugins/animate/animate.cpp#L221) for a usage example.

**Comment by damianatorrpm** [comment]
@ammen99 maybe we should close this and provide a default rule for matcher?

**Comment by ammen99** [comment]
We shouldn't close this until such an option is implemented :) Otherwise I agree.

**Comment by soreau** [comment]
I think the degrade *idea* is the way to go but it is incomplete. The problem with it that it causes pixel jitter when moving views and doesn't use mipmaps to get the best filtering possible. The following might work with much better performance:

- Generate mipmaps for the fb texture to be blurred
- Select an appropriate level of detail
- Blur the small(er) texture
- Scale it up to full screen size
- Blit the portion to be blended to a texture of view bounding box size
- Blend with view texture as usual

Perhaps the damage could be scaled to match the lower resolution mipmap texture for even more savings. I think this way, we'd get quality filtering done in hardware and hopefully, by addressing the entire fb as the texture to blur, this would eliminate the pixel jitter.
