### ISSUE TITLE
double clicking on decoration doesn't maximize

### ISSUE THREAD

**Issue by nodaba** [WayfireWM/wayfire#704]
double clicking on decoration doesn't maximize the window.
works with gtk programs though.

Thks 4 ur attention, interest & support.

**Comment by Arnaudv6** [comment]
I gave this a quick look. Double-click event is not used anywhere yet in wayfire it seems?
Also it requires delaying "move" event with a (x,y) threshold on [current_input](https://github.com/WayfireWM/wayfire/blob/master/plugins/decor/deco-layout.cpp#L225).
Time-wise, is there a ready to use function, a la wlr_keyboard_set_repeat_info(), that we should rely on in both:
https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/pointer.cpp
https://github.com/WayfireWM/wayfire/blob/master/src/core/seat/touch.cpp
I'd gladly help on that one, but I **do** understand if you don't want to babysit me.
I don't find it that easy, or am I making here harder than it needs to be?

**Comment by travankor** [comment]
>double clicking on decoration doesn't maximize the window.

Shouldn't you use the maximize button instead? Does KDE do this? Qt with CSD doesn't do this behavior.

**Comment by Arnaudv6** [comment]
> Shouldn't you use the maximize button instead? Does KDE do this? Qt with CSD doesn't do this behavior.

That's a classic behavior in openbox, gnome and all. Rationale is you don't need to aim for a (small and distant) button.

**Comment by ammen99** [comment]
@Arnaudv6 There is no such thing as double click handling in Wayfire, we get only a single click and release events and forward them to the clients. To implement this, you'll basically have to detect double click in the decoration plugin. A few starting points:

- Button press and release events coming to the decoration (probably not overly interesting here): https://github.com/WayfireWM/wayfire/blob/master/plugins/decor/deco-subsurface.cpp#L170
- Where the actual logic is: https://github.com/WayfireWM/wayfire/blob/master/plugins/decor/deco-layout.cpp#L225

How I'd go about implementing this: In the decoration layout, have a `wf::wl_timer`. Once the first click happens, start that timeout, if a second click comes before the timeout expires, well, you have a double-click event, return the action to the deco-subsurface.

Regarding move: I would change the mechanics a bit: make it so that clicking on the view once does not start moving it. Instead, make it so that if the user presses down a button and moves say 5 pixels while holding the mouse, then the move action is started.


Hope this helps :) 

PS. On why this is tagged as easy: It is not a lot of code, and you need knowledge of very few Wayfire or Wayland APIs to implement it.

**Comment by Arnaudv6** [comment]
> How I'd go about implementing this: In the decoration layout, have a `wf::wl_timer`. Once the first click happens, start that timeout, if a second click comes before the timeout expires, well, you have a double-click event, return the action to the deco-subsurface.

OK thanks for fast answer and wl_timer hint, I'll try to tackle this feature soonish™
