### ISSUE TITLE
[master] Some apps need 20-30 seconds to start

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#775]
*I'm not sure if it's a bug, or something wrong in my configuration, but I don't know where even to start. It only happens on one of my two laptops (Ryzen + 2 x amdgpu, Arch, ly DM). The other one (intel + integrated graphics, ArchLabs, sddm) behaves well.*

- If I **reboot** and log into wayfire, some apps (waybar, Caja, Thunar, nwggrid) need 20-30 seconds to start. It seems sometimes they don't start at all. Other apps (e.g. Chromium, mousepad, lxappearance, Alacritty, Azote) start normally.

- If I **reboot**, start sway, log out and start wayfire, everything works well.

**Comment by ammen99** [comment]
Try adding `0_environment = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY`.
The `0_environment` is just so that it is first in the alphabetical order and is run first.

**Comment by nwg-piotr** [comment]
You mean the `startwayfire` script?

**Comment by soreau** [comment]
You should put that in the autostart plugin config.

**Comment by nwg-piotr** [comment]
Ah, all right. It helps. Many thanks!

**Comment by damianatorrpm** [comment]
If someone comes across this you maybe also want 2_systemctl = systemctl --user import-environment
which needs to be run after 0_environment

**Comment by kode54** [comment]
Hi, that step is redundant, unless you are saying there are environment variables missing from the above command.

**Comment by damianatorrpm** [comment]
@kode54 They are not redundant.
Without the latter systemd.services that run GUI applicaitons don't see those.

**Comment by kode54** [comment]
Yes, and that dbus command with the `--systemd` argument does precisely the same thing.

**Comment by damianatorrpm** [comment]
If that's supposed to do so good, but it doesn't here.

**Comment by myfreeweb** [comment]
(note: the `--systemd` flag in `dbus-update-activation-environment` doesn't *require* systemd, so it's okay to always have it in autostart configs etc.)

Another completely unrelated reason something similar could happen (that probably very few other people will experience, but documenting for completeness):
if gvfs integration with gnome-online-accounts is broken ([as it is right now on FreeBSD](https://github.com/freebsd/freebsd-ports/commit/878144c423f07e76b0d945d50b1caedb8ec2d28e)) some GTK apps would stall for about 30 seconds waiting for g-o-a to reply, and `killall goa-daemon` can cancel the wait.

> If that's supposed to do so good, but it doesn't here.

Hmm. The [manpage](https://dbus.freedesktop.org/doc/dbus-update-activation-environment.1.html) suggests also adding `DBUS_SESSION_BUS_ADDRESS` to the list of variables, because systemd might not be aware of the d-bus session bus in your setup.

**Comment by affffc** [comment]
> If someone comes across this you maybe also want 2_systemctl = systemctl --user import-environment which needs to be run after 0_environment

After doing this flatpak gnome apps started respecting user theme settings. Thanks!

**Comment by LinArcX** [comment]
What about void linux users?

Void uses runit instead of systemd.

**Comment by ammen99** [comment]
> 0_environment = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY

Use this. The `--systemd` means 'also pass these env vars pass to systemd if it is present'
