### ISSUE TITLE
[multiheaded setup] The mouse pointer initially only visible on 1 of 3 displays

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wayfire#776]
This is a minor issue.

On my multi-headed setup

```
[DP-1]
layout = 0,0
(...)

[eDP-1]
layout = 1920,0
(...)

[HDMI-A-1]
layout = 3840,0
(...)
```

just started, the mouse pointer is only visible on `eDP-1`. Moving it between displays works (moves focus), but the pointer remains invisible **until I open a window anywhere**.

**Comment by soreau** [comment]
How about [this patch](http://ix.io/2AfK) for follow-focus?

**Comment by nwg-piotr** [comment]
I applied the patch, but dunno how to build:

```
$ meson build --prefix=/usr --buildtype=release
The Meson build system
Version: 0.55.3
Source dir: /home/piotr/Clones/wf-install/wayfire-plugins-extra
Build dir: /home/piotr/Clones/wf-install/wayfire-plugins-extra/build
Build type: native build
Project name: wayfire-plugins-extra
Project version: 0.5.0
C compiler for the host machine: cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35
C++ compiler for the host machine: c++ (gcc 10.2.0 "c++ (GCC) 10.2.0")
C++ linker for the host machine: c++ ld.bfd 2.35
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Found CMake: /usr/bin/cmake (3.18.4)
Run-time dependency wayfire found: NO (tried pkgconfig and cmake)

meson.build:16:0: ERROR: Dependency "wayfire" not found, tried pkgconfig and cmake

A full log can be found at /home/piotr/Clones/wf-install/wayfire-plugins-extra/build/meson-logs/meson-log.txt
```

**Comment by soreau** [comment]
Just rerun the script to install everything, then cd into wayfire-plugins-extra directory and apply the patch and run `ninja -C build && ninja -C build install`.

**Comment by nwg-piotr** [comment]
Thanks.

Yes, the patch resolves the issue.

**Comment by soreau** [comment]
This is because the client is what sets the cursor. Nothing in wayfire sets the cursor when it isn't over a surface, and there must be some bit that sets the cursor per output. So because you have to background app setting the cursor, this is what happens unless something sets it, like this patch does (sets the cursor to the default when pointer is over no surface).
I'm not sure follow-focus makes the best home for this feature but if the shoe fits..
I also wonder if there should be an option to toggle this behavior or if follow-focus should always set the cursor if it's enabled (would be easier to do the latter)

**Comment by nwg-piotr** [comment]
The follow-focus plugin is my must have, so it could be done this way IMO.

**Comment by ammen99** [comment]
#782 should fix this issue, right?

**Comment by nwg-piotr** [comment]
It does. Thank you!

**Comment by ammen99** [comment]
> It does. Thank you!

thanks @soreau :)
