### ISSUE TITLE
[switcher] bindings during active

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#839]
While switcher is activate clicking with the mouse on one of the views that are visible in switcher,
should activate that view. 
Also it would be good to be able to navigate with KEY_LEFT and KEY_RIGHT while switcher is 
active.

**Comment by ammen99** [comment]
Switcher does not work like that, it is keyboard-only and uses alt-tab and alt-shift-tab. It also exits immediately when you release the alt modifier (or super if that's what you have configured it with), and that is by design. It seems to me you want to use scale, it supports arrow keys and clicking on a view to focus :)
