### ISSUE TITLE
[wine-clients] CSD not always working

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#850]
example origin, should be worked around via plugin that listens and allows such configure events

**Comment by ammen99** [comment]
We discussed this on IRC. Xwayland clients should emit a request to the window manager so that it (in our case Wayfire) can start the dragging operation. Otherwise, things like aero-snapping the views with the move plugin and wobbly can't work.

The clients here in question do not emit such requests. Instead, they try to grab the mouse and change their position via configure requests. This is definitely not something desired on Wayland. Hence, this won't be fixed.

There is an easy workaround - just use the move plugin binding, you can then start move from any part of the window. A second possibility would be implementing a plugin which works around this:

1. Listen for new views
2. If it is xwayland, connect to its configure request event.
3. When configure request arrives, move the view in response. This might for example make the view go offscreen, so you should handle that and potentially move it to a different output, etc.
