### ISSUE TITLE
redraw behavior is worse without wobbly

### ISSUE THREAD

**Issue by damianatorrpm** [WayfireWM/wayfire#854]
The redrawing behavior of X views is bad in general (white space during resize and tiling),
with and without wobbly. I have attached a video link that shows that with wobbly (especially chrome, watch the bottom edge)
it's slightly better. It would be optimal if it were perfectly smooth with and without wobbly of course, hopefully no one who has epilepsy uses XWayland apps.

https://drive.google.com/file/d/1oM0cXpeS8lghDFN2fspgrIVBs3f9N0d-/view?usp=sharing

**Comment by ammen99** [comment]
This discussion (and the whole issue) is relevant: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1100#note_686545

Since it will work for some apps and not for others, and is a lot of work, I don't think it is worth it. If someone sends a PR which does not introduce too much complexity, I may reconsider.

**Comment by ammen99** [comment]
Reading the xserver issue, it doesn't seem like we can do something which really fixes the problem for all clients.
