### ISSUE TITLE
[invert] per-view keybinding

### ISSUE THREAD

**Issue by travankor** [WayfireWM/wayfire#920]
Let the invert plugin only invert a specific view. This shouldn't include the decoration (with SSD).

**Comment by ammen99** [comment]
I'd much rather implement a plugin which lets you attach custom shaders to views .. it would solve a much more general problem.
This is also in line with what I want for the fisheye/invert/zoom plugins, a single plugin where the user can add custom shaders ...

**Comment by soreau** [comment]
> Let the invert plugin only invert a specific view. This shouldn't include the decoration (with SSD).

I think this is a good idea.

> I'd much rather implement a plugin which lets you attach custom shaders to views .. it would solve a much more general problem.

This would be a good plugin, but..

> This is also in line with what I want for the fisheye/invert/zoom plugins, a single plugin where the user can add custom shaders ...

these plugins you mention are fullscreen shaders, not for individual views. The idea behind having a plugin is to have a complete idea in one place. Trying to cram all of these plugins into one sounds like you want to have one binding so that you can no longer activate these plugins individually, simultaneously. Also with different uniforms needing to be passed to each plugin and needing different rendering code in addition to shader code, the code will become a messy cocktail of different ideas in a hodgepodge. For invert single-view shader, this is also a different code concept (shading a view instead of fullscreen) so the code base would become that much more heavy.

I propose to make a new plugin which lets you attach custom shaders to views, but this is basically keycolor plugin with a few tweaks, so this should be the easiest path forward.

**Comment by soreau** [comment]
For invert specifically, it would probably make sense to convert the plugin to per-surface shader only. There could be toggle screen and toggle view bindings, and a match option for surfaces to ignore (shell applications are one example).

**Comment by soreau** [comment]
> You could make it work like the command plugin, you'd be able to set different bindings for different shaders. Also you say different plugins need different uniforms but so far we don't need mostly the same ones, it could work like shadertoy does (a set of standard uniforms for all shaders, maybe some of them unused).

If you have a plugin with different keybindings and options that do different things, they don't fit into the mold of a list, because they don't share common elements. For example, you say invert, fisheye and zoom can be in one plugin; and it could be, but you couldn't make a uniform list, considering the bindings and options are all different across plugins. You would only be combining the code and options into one mega-plugin that is more confusing to navigate and set options. Instead, I say keep the existing plugins that are in place and create this load-shaders-from-file plugin up to w-p-e.

**Comment by ammen99** [comment]
Not planned for the main repo.

**Comment by soreau** [comment]
There [now exists](https://github.com/soreau/filters) a way to apply a basic fragment shader to a view via ipc script.
