### ISSUE TITLE
read /etc/vconsole.confor /etc/default/keyboard for keyboard layout

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wayfire#935]
currently wayfire do not read /etc/vconsole.conf or /etc/default/keyboard to set its keyboard layout

this is a major issue especially when installing from calamares

https://github.com/calamares/calamares/blob/calamares/src/modules/keyboard/SetKeyboardLayoutJob.cpp

this creates a problem for users with non us layout

they have to go out of the way and set keyboard layout in wayfire.ini

it would be better if you can read from /etc/vconsole.conf or from /etc/deafult/keyboard instead

https://forum.garudalinux.org/t/no-swedish-keyboard-in-wayfire/1926

**Comment by ammen99** [comment]
You could simply override the Wayfire config defaults with an `.ini` file in `/etc/wayfire/defaults.ini` in your distro's installer.

Regarding `/etc/default/keyboard`: this seems to be a distro-specific file. I don't have such a file on Fedora, and there are potentially many other distros that don't support it.

Regarding `/etc/vconsole.conf`, it is definitely aimed at the virtual TTY, not the graphical desktop environment.

Because of these things, I do not want to implement support for this in Wayfire. Grepping into Mutter and Sway doesn't give me any results so I assume they don't read these files either. If you however do insist on using that approach, very soon you will be able to implement a custom config backend (#933), which can read these files, but you'll have to maintain that code yourself.

**Comment by marcusbritanicus** [comment]
@ammen99 This is rather painful don't you think? If each of wayland's compositors decided to use it's own config file for keyboard layouts, how many files an installer should write?

Rephrase: Can we have a configuration file that is respected by all wlroots based compositor, if not across wayland?

**Comment by marcusbritanicus** [comment]
The problem with 

> You could simply override the Wayfire config defaults with an .ini file in /etc/wayfire/defaults.ini in your distro's installer.

would be that a person may not start with installing wayfire - (s)he might start with the installation of xfce or lxqt (just saying as they are more common), set a keyboard layout a file called `/etc/wayfire/defaults.ini` will exist even if they never install wayfire at all. This is not really a nice thing is it?

Now, if we say, "create that file only if you are installing wayfire", that too would be wrong. Because there will be a lot of people who will start out with other DEs, set their own keymaps and then try out wayfire. For them, this file will not exist, which will make them feel rather disconnected with the rest of the system, as in, it does not support the keymap which "all other DEs" support. 

Rather than carry forward this bad situation (from user point of view) can we (all wayland or atleast wlr users and devs) to come to some consensus?

**Comment by ammen99** [comment]
Well if you want a solution which works cross-compositor, I'd first ask in #wayland on IRC to see what other DE people think about this problem. If everyone wants one of these files, then fine, we'll add this to Wayfire.

**Comment by myfreeweb** [comment]
DEs should use a first-run welcome prompt for configuring such things (and the prompt can offer defaults inferred from terminal config, x11 config, gnome `gsettings-desktop-schemas` etc.)

As Wayfire on its own is not a DE, that's out of scope of course :) But in whatever DE you build on top of Wayfire you can just do that.

**Comment by marcusbritanicus** [comment]
@myfreeweb Fair enough. But still it would be great if a system-wide config that works across all the wms. Just like you have one file for all X-based wms, we could either share such a file with them (ideal) or atleast have a separate file which is common to all wayland compositors. 

I am saying this because GNOME and Plasma being big distros coming from X will automatically support whatever file they used to read on X. the question that will arise is why "other wl compositors" don't support this.

PS: I asked in the #wayland channel. Waiting for a response from them.
